# Project Proposal
## Viktoria Basso

### Topic

I would like to investigate the relationship between 
wages from 1972 to 2020 in relation to the Consumer
Price Index (CPI). 

### Process of Proposal

I will retrieve this data in an 
Excel data file from the US Department of Labor 
Statistics ([here](https://www.bls.gov/data/)). 

I will perform descriptive statistics to find out the 
center, shape and spread of the mean wages, the CPI, 
and the subsections of mean wages based on highest 
education achieved. Next, I will perform a Pearson
Correlation with the main wage, and then each type of 
wage with CPI. 

Next, I will analyze the year, wage and CPI 
variables in a multiple linear regression. The response
variable will be wage and the predictors will be 
year and CPI. The purpose will be to see if we can 
predict wages from year and CPI.

All results will then be compiled and a data story
will be told in a website dependent on the results
of the analysis. The data story will include:

* A history of wages and Consumer Price Index
* A walk through of the analysis results and how they pertain to this history
* A conclusion that we can draw from my analysis to takeaway into the future.

### How does this Contribute to Your Understanding of R?

Skills that will be used:

* Importing data from USDL website (possibly using API)
* Cleaning the data in R so the data is ready for analysis
* Summary statistics for all of the continuous variables with box-and-whisker plots in R
* Performing a Pearson Correlation in R between continuous variables
* Creating a website in R to tell the history of wages and inflation, as well as provide output of my data